# Kilink configuration for production environment

server_host: linkode.org
db_engine: postgresql+psycopg2://{user}:{pass}@localhost/kilink
db_auth_config: configs/db_auth.txt
log_directory: /home/kilink/logs/production/
